### PR TITLE
Update simple-serialize.md

### PR DESCRIPTION
**Pull request by manoj398**
prefer & instead of %

### CODE REVIEW

**Comment by dapplion** [comment]
@manoj398 This change is motivated for performance reasons or readability?

**Comment by ralexstokes** [comment]
imo `% 8` is clearer and clarity is more important here than just about any other concern

**Comment by djrtwo** [comment]
Closing. Strong preference to not change something that people are used to reading without a more compelling reason to do so.

Happy to open it back up if there are further discussion points.

**Comment by manoj398** [comment]
If the readability is the concern, imo it should be bitarray or boolean array instead of bytearray.

**Pull request closed without merging**
