### PR TITLE
Remove post-altair `initialize_beacon_state_from_eth1` from specs

### PR DESCRIPTION
**Pull request by KatyaRyazantseva**
This PR removes post-altair `initialize_beacon_state_from_eth1` from specs.

Issue addressed #3663

### CODE REVIEW

**Comment by KatyaRyazantseva** [comment]
@hwwhww when deleting `initialize_beacon_state_from_eth1` from bellatrix, `test_initialize_post_transition` and `test_initialize_pre_transition_empty_payload` in `test_initialization.py` fail caused by the lack of `execution_payload_header` param. What's the better approach to solve this?

https://github.com/KatyaRyazantseva/consensus-specs/blob/8facc0a095a3fca85dcec984bbbd29f61c763897/tests/core/pyspec/eth2spec/test/bellatrix/genesis/test_initialization.py#L115
https://github.com/KatyaRyazantseva/consensus-specs/blob/8facc0a095a3fca85dcec984bbbd29f61c763897/tests/core/pyspec/eth2spec/test/bellatrix/genesis/test_initialization.py#L79

**Comment by KatyaRyazantseva** [comment]
@hwwhww  electra and eip-7594 ci tests fail, because `add_validator_to_registry(state, pubkey, withdrawal_credentials, Gwei(0))` in apply_deposit() leaves state.balances empty. This change has been marked as Modified in Electra:EIP7251. It causes some assertion failures like `assert spec.is_valid_genesis_state(state)` and others. I found the same failures in the dev branch when running citest.  Example:
```
def initialize_beacon_state_from_eth1(eth1_block_hash: Hash32,
                                      eth1_timestamp: uint64,
                                      deposits: Sequence[Deposit]) -> BeaconState:
    fork = Fork(
    ....
        for index, validator in enumerate(state.validators):
            # balances are empty
            balance = state.balances[index] 
            # validator's effective balance is empty, validator is not active
            validator.effective_balance = min(balance - balance % EFFECTIVE_BALANCE_INCREMENT, 
                  MAX_EFFECTIVE_BALANCE) 
            if validator.effective_balance == MAX_EFFECTIVE_BALANCE:
                validator.activation_eligibility_epoch = GENESIS_EPOCH
                validator.activation_epoch = GENESIS_EPOCH

```

**Comment by dapplion** [comment]
@KatyaRyazantseva there appears to be an involuntary commit of `.idea` files

**Comment by hwwhww** [comment]
@KatyaRyazantseva 

Suggestions:
1. remove `tests/core/pyspec/eth2spec/test/bellatrix/genesis/test_initialization.py` file since it is no longer relevant
2. for the test cases in `tests/core/pyspec/eth2spec/test/phase0/genesis/test_initialization.py`, replace `@with_all_phases` with `@with_phases([PHASE0])` so that we only test `initialize_beacon_state_from_eth1` helper with Phase0.

**Review by hwwhww — APPROVED** [review]
LGTM! 👍

No more redundant `initialize_beacon_state_from_eth1` when writing a new feature!

**Review by jtraglia — APPROVED** [review]
LGTM 👍

**Pull request merged**
