### PR TITLE
Compute aggregate kzg proofs now takes the commitments as a parameter.

### PR DESCRIPTION
**Pull request by kevaundray**
This is a draft PR that arose from speaking with Dankrad.

The idea here is that (paraphrasing Dankrad): Each blob transaction will contain the commitment to that blob, so when one is building a block, they do not need to recompute the commitments from the blobs.

Questions to consider:

- Is it okay if we are supplied incorrect KZG commitments (ie what if one supplies the identity point with a kzg commitment)?

- Can we be sure that `block.kzg_commitments` will always contain the commitments in the right order (transaction order)?

### CODE REVIEW

**Comment by dankrad** [comment]
> Is it okay if we are supplied incorrect KZG commitments (ie what if one supplies the identity point with a kzg commitment)?

The identity point *is* a valid KZG commitment for the blob that is all zeros.

Further to this, transaction validation will already verify that a blob comes with a valid commitment through the point check.

**Review by ralexstokes — APPROVED** [review]
> Can we be sure that block.kzg_commitments will always contain the commitments in the right order (transaction order)?

as written, if you have a conformant implementation to the spec, you'll get everything in the correct order

the more computation we can skip on the block production path, the better and this changes makes sense to me

**Comment by dankrad** [comment]
> as written, if you have a conformant implementation to the spec, you'll get everything in the correct order

I don't think there is a check on this, so I don't think we can make that assumption for blocks someone else has created.

**Comment by ralexstokes** [comment]
yeah, I was going off the language for the `get_blobs_and_kzg_commitments` spec; if it is not agreed that this API returns the data in the correct order then we should probably make that explicit

**Comment by kevaundray** [comment]
Closing as this is now done in #3280

**Pull request closed without merging**
