### PR TITLE
WIP: Update dockerisation

### PR DESCRIPTION
**Pull request by parithosh**
This PR adds a script to run the tests inside a Docker container. Ideally we can move to using a containerized environment for all the tests in the future, but the script is a good first step at gathering user feedback. 

The PR adds a standalone `Dockerfile`, this file just sets up the dependencies required to run the tool and can be used independently. The docker image can be locally built with:
- `docker build ./ -t $IMAGE_NAME -f ./docker/Dockerfile` will build the docker container
- `docker run -it $IMAGE_NAME /bin/sh` will give you a shell inside the docker container to manually run any tests
- `docker run  $IMAGE_NAME make citest` will run the `make citest` command inside the docker container
- Ideally manual running of docker containers is for advanced users, we recommend the script for most users

There is additionally a `scripts/build_run_docker_tests.sh` script which covers most regular usecases. The script allows the user to configure the `fork`(altair/bellatrix/capella..), `image_name`(specifies the container to use), `number of cores`, `preset type`(mainnet/minimal) and `test all forks` flags. Ideally this is the main way that users interact with the spec tests, instead of running it locally. 

E.g:
- `./build_run_test.sh --p mainnet --n 16` will run the mainnet preset tests with 16 threads
- `./build_run_test.sh --a` will run all the tests across all the forks
- `./build_run_test.sh --f deneb --n 16` will only run deneb tests on 16 threads

Results are always placed in a folder called `./testResults`. The results are `.xml` files and contain the fork they represent and the date/time they were run at.

### CODE REVIEW

**Comment by mrthankyou** [comment]
@parithosh,

Do you need any additional help on this PR? This is semi-blocking for me as I would like to write some tests for consensus-spec and this would make my work much easier :).

**Comment by parithosh** [comment]
Sorry I haven't had much time to look into the topic since the initial commits. I'll try and assign some time next week to close up the topic.

**Comment by mrthankyou** [comment]
Happy to help and save you time any way I can. Just let me know!

**Comment by parithosh** [comment]
cc @hwwhww @dapplion @mrthankyou 

Sorry for the delay on this PR, let me know what you think and how it works for you.

**Review by hwwhww — APPROVED** [review]
@parithosh Tested locally and LGTM! 👏

p.s. It's probably better to squash merge it

**Comment by parithosh** [comment]
would it make sense to add a small usage/installation guide in the main README as well?

**Pull request merged**
