### PR TITLE
Use 32-bit random value in validator filter

### PR DESCRIPTION
**Pull request by jtraglia**
See: https://docs.google.com/spreadsheets/d/18VeMVLO1jbP8xHkT4faGEb5SyrWQhQLcU-BtsL9pTss

This fixes an oversight in `compute_proposer_index` and `get_next_sync_committee_indices`.

Currently, we use an 8-bit random byte to perform an effective balance filter. This was used to penalize validators with effective balances less than 32 ETH. But now that we have raised the maximum effective balance, this mechanism plays a more important role in validator selection.

One might expect a validator with a greater effective balance to have a greater chance of being selected as proposer or sync committee participant, but no. This is because the random byte can only represent 256 "buckets" of effective balance. So for example, currently, a validator with 33 ETH has the same likelihood of being selected as a validator with 40 ETH, because these validators are in the same bucket.

The solution is to use a bigger random value to allow more precision. I propose we use a 32-bit random value instead which provides more than enough precision. But this change requires we use "effective balance increments" instead of Gwei in the calculation because the latter could cause an integer overflow when multiplying the values together.

### CODE REVIEW

**Comment by mkalinin** [comment]
A thought: we can sample 16-bit value instead to prevent overflow and to sample twice as more values comparing to 32-bit case with a single hash computation. 16-bit value should also give enough of a granularity and have a smaller impact on the logic

**Comment by jtraglia** [comment]
> A thought: we can sample 16-bit value instead to prevent overflow and to sample twice as more values comparing to 32-bit case with a single hash computation. 16-bit value should also give enough of a granularity and have a smaller impact on the logic

Hmm yes. I think this is the right decision. I'm going to close this PR & make a new one. Thank you 🙏

**Comment by alialobidm** [comment]
> ``

**Review by alialobidm — COMMENTED** [review]
``

**Pull request closed without merging**
