### PR TITLE
Upgrade `wheel`, `pip`, and `setuptools` with `make install_test`

### PR DESCRIPTION
**Pull request by hwwhww**
In the process of debugging the CI failure in #3442. We're now updating to the latest versions of `wheel`, `pip`, and `setuptools` at the beginning of the `make install_test` command.

### CODE REVIEW

**Comment by hwwhww** [comment]
I realized that we have to detect the pip upgrade *and* update the CI cache accordingly. Probably make more sense to pin the version in the CI configuration.

**Comment by djrtwo** [comment]
Pinning usually seems safer than upgrading to an arbitrary latest

**Comment by hwwhww** [comment]
@djrtwo 
To make it a bit more flexible, I changed it to only set minimum version requirements here.

**Review by djrtwo — APPROVED** [review]
looks good

**Pull request merged**
