### PR TITLE
more granular reward/penalties

### PR DESCRIPTION
**Pull request by djrtwo**
addresses #205

### CODE REVIEW

**Comment by JustinDrake** [comment]
In "Per-epoch processing" I suggest creating a "Rewards and penalties" section with the following subsections:

* Justification and finalisation
* Activity and inactivity (rename `INCLUDER_REWARD_QUOTIENT` to `ACTIVITY_REWARD_QUOTIENT`?)
* Crosslinks

Other suggestions:

* Put all the rewards and penalties helpers (e.g. `base_reward_quotient`, `base_reward`, `base_inactivity_penalty`) in the "Rewards and penalties" section
* Put the "Rewards and penalties" section at the end of "Per-epoch processing"

**Comment by djrtwo** [comment]
Saving the following for another PR:

* Put the "Rewards and penalties" section at the end of "Per-epoch processing"
* Put the logic under "# Calculate penalties for slashed validators" in the "Rewards and penalties" section

**Comment by JustinDrake** [comment]
Does it make sense to break off the inactivity penalties (current under "Justification and finalization") into it's own subsection?

**Comment by JustinDrake** [comment]
Maybe also put `base_inactivity_penalty` into "Inactivity penalty".

**Comment by djrtwo** [comment]
All of the justification/finalization penalties are activity/inactivity penalties (all in the context of whether justification and finalization are occuring)

**Pull request merged**
