### PR TITLE
Adds cronjob for test vector generation

### PR DESCRIPTION
**Pull request by parithosh**
This PR will trigger the generate vectors job nightly at 2AM and upload the results as a job artifact. These artifacts can be consumed by anyone who relies on nightlies, with the knowledge that the tests haven't been verified or sanity checked (that only happens on releases).

### CODE REVIEW

**Review by jtraglia — APPROVED** [review]
Good idea! Just to be clear, is this 2am UTC time?

**Comment by parithosh** [comment]
> Good idea! Just to be clear, is this 2am UTC time?

Yeah exactly, Scheduled workflows always run on UTC time :D

**Review by hwwhww — APPROVED** [review]
Thank you @parithosh!

Can every logged-in user access the artifacts? Or only the maintainers?

**Comment by parithosh** [comment]
> Thank you @parithosh!
> 
> Can every logged-in user access the artifacts? Or only the maintainers?

Every user can access the artifacts, even without logging in. So it should be easy for anyone to setup a CI to consume the result

**Pull request merged**
