### PR TITLE
[KZG] Serialize roots of unity as hex as well

### PR DESCRIPTION
**Pull request by mratsim**
This serializes the roots_of_unity as hex as well.

Most JSON readers would fail to deserialize a bigint encoded as int and while most cryptographic libraries have a hex->internal_repr converter, many don't have a decimal->internal_repr converter, in particular BLST.

### CODE REVIEW

**Comment by hwwhww** [comment]
> bigint encoded

In CL specs, we use SSZ to define `ROOTS_OF_UNITY` as a `Vector[BLSFieldElement, FIELD_ELEMENTS_PER_BLOB]` type. Although I support that `polynomial-commitments.md` should actually be independent of SSZ as it's laid in a cryptography black box, I feel it's more consistent to use SSZ serialization for preset in this case at the current stage.

^^^ However, it may be messier per #3354. 🫨

**Comment by CarlBeek** [comment]
I agree with @mratsim that these should be hex-encoded. On top of that, I'm not convinced these should be a JSON file either. As was discussed at Edelweiss, most crypto libraries won't have a JSON parser, so it seems prudent to have an even flatter (text) file.

**Review by djrtwo — COMMENTED** [review]
Where do we stand here @CarlBeek ?

**Comment by hwwhww** [comment]
closing via #3521

**Pull request closed without merging**
