### PR TITLE
Replace "updated" with "modified" in Electra spec

### PR DESCRIPTION
**Pull request by jtraglia**
This PR does the following:

* Replace usages of "updated" with "modified" to be consistent with previous specs.
* For modified functions, ensure there is a note about the changes.
  * I updated some of these notes to be consistent with other specs.
  * Some of these notes could be better 😅
* Delete notes for new functions as we don't normally do this.
  * This was for `process_withdrawal_request` and `process_deposit_request`.
* Replace "NOTE" with "Note" and "Electra:EIP-7251" with "Electra:EIP7251" for consistency.
* Fix some excess blank lines & missing blank line nits.

### CODE REVIEW

**Review by mkalinin — APPROVED** [review]
LGTM!

**Review by ralexstokes — APPROVED** [review]
great thanks!

**Comment by ralexstokes** [comment]
@jtraglia I tried to save you some work by fixing a rebase in the web UI but it looks like I messed something up w/ the TOC


if you can plz fix im happy to merge this in, may just want to drop my commit and handle the conflicts that way

**Comment by jtraglia** [comment]
> if you can plz fix im happy to merge this in, may just want to drop my commit and handle the conflicts that way

No worries! It was a simple fix. I think we should be good now.

**Pull request merged**
