### PR TITLE
chore: try add small optimizations to divide_polynomialcoeff

### PR DESCRIPTION
**Pull request by kevaundray**
This adds three optimizations:

- Replace `.insert(0,x)` with `.append(x)` and then a `.reverse`. Inserting at the first index on each loop causes every item in the list to be shifted down by one at each loop iteration.

- `return [x % BLS_MODULUS for x in o]` to `return o` . The values of `o` should already be reduced since they are coming from the `div` function.

- (a - b + modulus) becomes (a + (modulus - b)) - This mainly a nit, as the order of operations is not entirely clear.

### CODE REVIEW

**Comment by kevaundray** [comment]
This shaves off around 2 minutes from the 7594 tests (looked at other PRs to see how long they took compared to this)

**Review by asn-d6 — APPROVED** [review]
This looks correct to me!

I'm approving but not merging, in case we want to discuss this further. Also curious how much each of the three (two?) optimizations contribute to the overall performance improvement: "returning o" is a clear improvement in performance and readability, whereas the append/reverse is slightly non-trivial (still fine though).

**Comment by kevaundray** [comment]
Good points -- I'm happy to leave this open until there's consensus

**Comment by jtraglia** [comment]
This doesn't appear to be faster (compare the 1st and 3rd images). I think GitHub CI runs aren't always run on the same hardware and/or have less priority. The same run can vary by a few mins.

<details>
<summary>Click to see some CI runs</summary>

image

image

image

image

image

image

</details>

So I think we should close this PR, as the original code is easier to read.

**Comment by kevaundray** [comment]
Most of the changes have been superceded by changing to bls.Scalar it seems, so happy to close!

**Pull request closed without merging**
