### PR TITLE
Remove extraneous length check from deneb forkchoice

### PR DESCRIPTION
**Pull request by ralexstokes**
Remove duplicate check:

`verify_blob_kzg_proof_batch` checks that `len(expected_kzg_commitments) == len(blobs) == len(proofs)` so it is duplicate to have here.

I'd say we assume this functionality is part of the API of `verify_blob_kzg_proof_batch` and if so we can remove this check here and also under the `validator.md` guide.

What do we think @asn-d6 @jtraglia @hwwhww ?

### CODE REVIEW

**Review by jtraglia — APPROVED** [review]
I think that's a fair assumption. LGTM 👍

**Review by terencechain — APPROVED** [review]

**Comment by hwwhww** [comment]
I git-blamed it. This helper had more assertions before the blob decoupling.

@ralexstokes 
Unless we do want to extend `validate_blob` content later, it would be simpler if we just remove `validate_blob` and use `verify_blob_kzg_proof_batch` directly in `is_data_available`.

**Comment by dapplion** [comment]
PR title should be something meaningful

**Review by djrtwo — APPROVED** [review]

**Review by Sammiegirl411 — COMMENTED** [review]
Try

**Pull request merged**
