### PR TITLE
EIP4844: Enable withdrawal

### PR DESCRIPTION
**Pull request by terencechain**
Given EIP4844 is decoupled from Shanghai and targeted for Cancun, and with the withdrawal spec almost finalized, it'd make sense to enable withdrawal for the subsequent 4844 devnets. This is more realistic to what the final product would look like, and it's cleaner for the client implementations, the less "custom" code, the better.

No rush to merge this. I think we can target this for devnet4.

### CODE REVIEW

**Review by g11tech — APPROVED** [review]
lgtm!

**Review by dapplion — APPROVED** [review]

**Comment by djrtwo** [comment]
I'm cool leaving this as a placeholder but there is quite a bit of testing code to re-enable before this gets merged.

And for the record, I too would like to get this back into it's final form as soon as is feasible

**Comment by hwwhww** [comment]
Update: per the EIP-4844 call decision (https://github.com/ethereum/pm/issues/701), let's aim to include it in the next release!

I pushed commits to update the tests. Now running the testgen. I will review it again tomorrow.

**Review by hwwhww — APPROVED** [review]
Test vectors look good to me. Really glad that we can finally remove the no-op 🥳

p.s. we are testing and fixing the new GitHub Actions CI integration. Please ignore the weird GitHub Actions lint error.
CircleCI still covers all tests.

**Comment by terencechain** [comment]
Thanks so much @hwwhww !

**Review by djrtwo — APPROVED** [review]
looks good!

**Pull request merged**
