### PR TITLE
Modify `hash_to_bls_field` logic

### PR DESCRIPTION
**Pull request by hwwhww**
Address #2980: replace `hash_tree_root(x)` with `hash(ssz_serialize(x))`.

### CODE REVIEW

**Review by protolambda — APPROVED** [review]

**Comment by dankrad** [comment]
I understand that this improves performance by 2x. This is due to the fact that sha256 of 2*32 bytes hashes a total of 2 blocks, which is 4*32 bytes; if this were not the case, hash_tree_root would have about the same performance as a plain hash, but it is much more parallelizable. 

But it would be important to know the baseline that we are comparing this to.

So far we have had a rule that we don't use serialization inside the spec (though the merge might break that rule already, haven't checked).

**Comment by hwwhww** [comment]
@dankrad @asn-d6 

> So far we have had a rule that we don't use serialization inside the spec (though the merge might break that rule already, haven't checked).

FYI (dank)sharding spec uses [`ssz_serialize()` in `process_sharded_data` function](https://github.com/ethereum/consensus-specs/blob/4370f30b99142d92bf676f0ee6a0aa74f688f891/specs/sharding/beacon-chain.md#sharded-data
).

Also, since `hash_to_bls_field` was copied from sharding spec, if we decide to apply this PR, we may want to update [sharding spec function](https://github.com/ethereum/consensus-specs/blob/4370f30b99142d92bf676f0ee6a0aa74f688f891/specs/sharding/polynomial-commitments.md) as well.  And either way, we should update the function name to `hash_to_bls_field_with_challenge_number` due to the name conflict.

**Comment by ppopth** [comment]
I think it's a good idea to put why we must not use `hash_tree_root` in the comment in the code. (probably put the issue link in the comment)

**Comment by hwwhww** [comment]
@ppopth 

I think it's fine to add comments, but not sure about adding the issue link since we never add issue links to specs before. My life depends on git blame a lot though. 😅

**Review by asn-d6 — APPROVED** [review]
LGTM!

**Comment by asn-d6** [comment]
Merged this as is! Thanks for the patch @hwwhww . For more details on how this impacts performance see https://github.com/ethereum/consensus-specs/issues/2980#issuecomment-1222562583

WRT the sharding spec changes suggested in https://github.com/ethereum/consensus-specs/pull/2981#issuecomment-1223993792, I think we should handle these in a different ticket. Both for the sake of progressing this more-urgent ticket faster, but also because I think there is gonna be a big banch of 4844 changes that should be folded in the sharding spec (since 4844 became executable).

WRT the comment suggestion in https://github.com/ethereum/consensus-specs/pull/2981#issuecomment-1225361541, I think it's OK to leave it as is. I think comments about design choices that _were not taken_ might confuse code readers who are mainly interested in the design choices that were taken (also, as @hwwhww said, a git-blame should bring them here. Hey!).

**Pull request merged**
