### PR TITLE
Remove `is_execution_enabled` condition since Capella

### PR DESCRIPTION
**Pull request by hwwhww**
Related issue: #3232

### Issue
I would argue that the Bellatrix `is_execution_enabled` condition check is technical debt that we can remove now. Since this condition is surely satisfied on the mainnet, the benefits of having the ability to support the "not-merged-beacon-chain" testnets are inessential.

### How did I fix it
- Remove the `is_execution_enabled` check since Capella.
- Update the spec tests accordingly 

This is a substantive beacon chain change but backward-compatible with the Ethereum mainnet.

### CODE REVIEW

**Comment by mkalinin** [comment]
I am in favour of this change as neither Capella nor Deneb can't be taken into effect without execution being enabled, thus, they are dependent on Bellatrix. The only scenario when `is_execution_enabled` can still be relevant is a simultaneous activation of Bellatrix and Capella, and potentially Deneb. I doubt any testnet requires this type of upgrade, likewise, any mainnet accepting risks related to a bundled update of this kind.

Do we also want to remove `validate_merge_block` from Deneb FC spec?

**Comment by potuz** [comment]
+1 on removing merge block validation.

**Comment by hwwhww** [comment]
@mkalinin 
> Do we also want to remove validate_merge_block from Deneb FC spec?

Yes, this PR and #3232 should be considered together. 👍
And I'm in favor of updating them from Capella.

**Comment by mkalinin** [comment]
I think that this change should also get rid of `is_merge_transition_complete` check in the `process_execution_payload`

**Review by djrtwo — APPROVED** [review]

**Pull request merged**
