### PR TITLE
Update compute_el_header_block_hash for EIP-7685

### PR DESCRIPTION
**Pull request by jtraglia**
Reference: https://eips.ethereum.org/EIPS/eip-7685

This PR does the following:

* Consolidate `deposit_receipts` and `withdrawal_requests` into `requests`.
* When encoding those two types, prefix with type (`0x00` and `0x01`).
* Encode with non-null `parent_beacon_root`.
  * A null `parent_beacon_root` causes issues when `requests_root` is not null.
  * I believe this field was accidentally overlooked before.
* Set `payload.withdrawal_requests = []` in  `build_empty_execution_payload`.

I noticed these issues when looking into why the block hash differed from Geth.

### CODE REVIEW

**Comment by jtraglia** [comment]
@lightclient I would appreciate your review but I can't select you as a reviewer.

**Review by mkalinin — COMMENTED** [review]
The logic looks correct to me. One nit: `get_deposit_receipt_rlp` (same with withdrawal requests) returns Request encoding which is not an RLP because of the type byte at the beginning, consider renaming these methods to reflect their actual semantics.

**Comment by jtraglia** [comment]
> consider renaming these methods to reflect their actual semantics.

Ah yes, you're right. Thanks for pointing this out! I took this approach.

**Comment by hwwhww** [comment]
Note: if #3757 gets merged, we should rename it in this PR too.

**Review by hwwhww — APPROVED** [review]
@jtraglia I fixed the conflicts and added lines for `ConsolidationRequest`. Could you take a look?

**Comment by jtraglia** [comment]
> @jtraglia I fixed the conflicts and added lines for `ConsolidationRequest`. Could you take a look?

@hwwhww So `get_withdrawal_request_rlp_bytes` and `get_consolidation_request_rlp_bytes` are both prefixed with `0x01` now, these should be different. And `get_deposit_request_rlp_bytes` doesn't have a prefix byte anymore.

**Comment by hwwhww** [comment]
@jtraglia you're right! I forget to update the prefix when copy-pasting.

**Pull request merged**
