### PR TITLE
EIP-7732: Refactor Beacon chain state transition function

### PR DESCRIPTION
**Pull request by StefanBratanov**
Move `process_execution_payload` to new `Execution payload processing` section to separate it from `Block processing`

### CODE REVIEW

**Review by Gulrizwan23 — APPROVED** [review]

**Review by Gulrizwan23 — APPROVED** [review]
specs/_features/eip7732/beacon-chain.md

**Review by Gulrizwan23 — COMMENTED** [review]
-

**Review by potuz — APPROVED** [review]
LGTM thanks! hope conflicts on #3854 aren't that bad

**Review by jtraglia — APPROVED** [review]
LGTM 👍 thank you!

**Review by Gulrizwan23 — COMMENTED** [review]
Modified version

**Review by Gulrizwan23 — COMMENTED** [review]
Go

**Review by Gulrizwan23 — COMMENTED** [review]
****

**Pull request merged**
